version: '3.8'

services:
  searchgpt-backend:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DEBUG=False
      - SELENIUM_TIMEOUT=120
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - SEARCH_RESULTS_LIMIT=20
      - MAX_PAGES_TO_SCRAPE=20
      - PYTHONUNBUFFERED=1
    volumes:
      - ./debug:/app/debug
    restart: unless-stopped